services:
    backend:
        image: backend
        build: 
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    db:
        image: postgres:13
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./data:/var/lib/postgres/data
    cache:
        image: redis:alpine
        volumes:
            - ./cache:/data
        ports:
            - '6379:6379'
    rabbitmq:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=guess
            - RABBITMQ_DEFAULT_PASS=guess
        ports:
            - "5672:5672"
    frontend:
        image: frontend
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            - VUE_APP_BACKEND_URL=http://localhost:8080
    nginx:
      image: nginx:latest
      depends_on:
        - backend
      ports:
        - 8000:8000
      volumes:
        - ./nginx/conf.d:/nginx/conf.d